# config/config_pytorch.yaml

data:
  raw_source: "sklearn_iris"
  new_data_dir: "../data/new"
  processed_dir: "../data/processed"

training:
  test_size: 0.2
  random_seed: 42
  batch_size: 16
  num_epochs: 20
  learning_rate: 0.001
  hidden_dim: 16
  mlflow_experiment: "iris_nn_experiment"

evaluation:
  # no extra parameters

tuning:
  param_grid:
    hidden_dim: [8, 16, 32]
    learning_rate: [0.01, 0.001, 0.0001]
    num_epochs: [10, 20]
    batch_size: [16, 32]
